#!/usr/bin/env python3
"""Regenerate course indexes from per-page frontmatter + _course.yml.

Usage:
    uv run python scripts/build_course_index.py courses/ais
    uv run python scripts/build_course_index.py --all
    uv run python scripts/build_course_index.py --all --watch
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import yaml


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    return yaml.safe_load(text[4 : end + 1]) or {}


def strip_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---", 4)
    if end == -1:
        return text
    rest = text[end + 4 :]
    return rest.lstrip("\n")


BODY_PARTIAL = "_body.qmd"
BACK_LINK_BEGIN = "<!-- AUTOGENERATED-BACK-LINK -->"
BACK_LINK_END = "<!-- /AUTOGENERATED-BACK-LINK -->"


def html_comment(lines: list[str]) -> str:
    return "\n".join(f"<!-- {line} -->" for line in lines) + "\n"


def relative_script_link(from_dir: Path, root: Path) -> str:
    return Path(
        *([".."] * len(from_dir.relative_to(root).parts)),
        "scripts/build_course_index.py",
    ).as_posix()


def strip_back_link(text: str) -> str:
    start = text.find(BACK_LINK_BEGIN)
    if start == -1:
        return text
    end = text.find(BACK_LINK_END, start)
    if end == -1:
        return text
    end += len(BACK_LINK_END)
    # also consume trailing newline(s) after the end marker
    while end < len(text) and text[end] == "\n":
        end += 1
    return text[:start] + text[end:]


def linkify_first_heading(body: str, slug: str) -> str:
    lines = body.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("# "):
            title = line[2:].strip()
            html_block = (
                '::: {.content-visible when-format="html"}\n'
                f"# [{title}]({slug}/index.qmd)\n"
                ":::"
            )
            other_block = (
                '::: {.content-hidden when-format="html"}\n'
                f"# {title}\n"
                ":::"
            )
            lines[i] = html_block + "\n\n" + other_block
            break
    return "\n".join(lines)


def write_body_partial(page_dir: Path, slug: str) -> Path:
    src = page_dir / "index.qmd"
    body = strip_frontmatter(src.read_text(encoding="utf-8"))
    body = strip_back_link(body)
    body = linkify_first_heading(body, slug)
    root = next(parent for parent in page_dir.parents if (parent / "scripts").exists())
    script_link = relative_script_link(page_dir, root)
    course_index_link = "../" * len(Path(slug).parts) + "index.qmd"
    header = html_comment(
        [
            "AUTOGENERATED: lesson body partial included into the full course page.",
            f"Generator: {script_link}",
            "Source: index.qmd in this directory.",
            f"Included by: {course_index_link}",
            "Transformation: YAML frontmatter is stripped,",
            "the autogenerated back-link block is removed, and the first H1 is linkified.",
            "Do not edit this file by hand; edit index.qmd and regenerate.",
        ]
    )
    out = page_dir / BODY_PARTIAL
    new = header + body
    prev = out.read_text(encoding="utf-8") if out.exists() else ""
    if prev != new:
        out.write_text(new, encoding="utf-8")
    return out


def inject_back_link(page_dir: Path, slug: str) -> None:
    src = page_dir / "index.qmd"
    text = src.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return
    end = text.find("\n---", 4)
    if end == -1:
        return
    fm_end = end + 4  # position right after the closing '---'
    rest = text[fm_end:].lstrip("\n")
    rest = strip_back_link(rest)

    depth = len(Path(slug).parts)
    up = "../" * depth + "index.qmd"
    block = (
        f"{BACK_LINK_BEGIN}\n"
        '::: {.content-visible when-format="html"}\n'
        f"[← Обратно к курсу]({up}){{.back-to-course}}\n"
        ":::\n"
        f"{BACK_LINK_END}\n"
    )
    new_text = text[:fm_end] + "\n\n" + block + "\n" + rest
    if new_text != text:
        src.write_text(new_text, encoding="utf-8")


def collect_pages(course_dir: Path) -> list[dict]:
    pages: list[dict] = []
    for idx in course_dir.rglob("index.qmd"):
        if idx == course_dir / "index.qmd":
            continue
        fm = parse_frontmatter(idx)
        if fm.get("draft"):
            continue
        if "module" not in fm or "order" not in fm or "title" not in fm:
            continue
        rel = idx.parent.relative_to(course_dir).as_posix()
        pages.append(
            {
                "slug": rel,
                "title": fm["title"],
                "module": fm["module"],
                "order": fm["order"],
            }
        )
    pages.sort(key=lambda p: parse_order_key(p["order"], p["module"]))
    return pages


def normalize_module_order(module: int | str) -> int:
    if isinstance(module, int):
        return module
    if isinstance(module, str) and module.isdigit():
        return int(module)
    if module == "extra":
        return 10_000
    raise ValueError(f"unsupported module value: {module!r}")


def parse_order_key(order: int, module: int | str) -> tuple[int, int]:
    module_order = normalize_module_order(module)

    if isinstance(order, int):
        return (module_order, order)
    if isinstance(order, str) and order.isdigit():
        return (module_order, int(order))

    raise ValueError(
        f"unsupported order value: {order!r}; expected numeric encoding like 2006 or 9001"
    )


def render(manifest: dict, pages: list[dict], course_dir: Path) -> str:
    by_module: dict = {}
    for p in pages:
        by_module.setdefault(p["module"], []).append(p)

    try:
        course_arg = course_dir.relative_to(Path.cwd()).as_posix()
    except ValueError:
        course_arg = course_dir.as_posix()

    lines: list[str] = []
    lines.append("---")
    lines.append(f'title: "{manifest["title"]}"')
    lines.append("format:")
    lines.append("  html:")
    lines.append("    toc: true")
    lines.append("  typst:")
    lines.append("    toc: true")
    lines.append("---")
    lines.append("")
    lines.append(
        html_comment(
            [
                "AUTOGENERATED: full single-page course index and printable/PDF source.",
                "Generator: ../../scripts/build_course_index.py",
                "Sources: _course.yml for course/module metadata; **/index.qmd frontmatter for",
                "lesson order/title/module; **/_body.qmd files generated from lesson bodies.",
                f"Regenerate with: uv run python scripts/build_course_index.py {course_arg}",
                "Do not edit this file by hand; edit the sources above and regenerate.",
            ]
        ).rstrip()
    )
    lines.append("")
    if manifest.get("intro"):
        lines.append(manifest["intro"].rstrip())
        lines.append("")

    lines.append('::: {.content-visible when-format="typst"}')
    lines.append("")
    lines.append("## Оглавление")
    lines.append("")
    counter = 1
    for m in manifest["modules"]:
        items = by_module.get(m["id"], [])
        if not items:
            continue
        lines.append(f"**{m['title']}**")
        lines.append("")
        if m.get("list_only"):
            for p in items:
                lines.append(f"- [{p['title']}]({p['slug']}/index.qmd)")
        else:
            for p in items:
                lines.append(f"{counter}. [{p['title']}]({p['slug']}/index.qmd)")
                counter += 1
        lines.append("")
    lines.append(":::")
    lines.append("")

    for m in manifest["modules"]:
        items = by_module.get(m["id"], [])
        if not items or m.get("list_only"):
            continue
        lines.append("---")
        lines.append("")
        if m.get("intro"):
            lines.append("::: {.module-intro}")
            lines.append(f"# {m['title']}")
            lines.append("")
            lines.append(m["intro"].rstrip())
            lines.append(":::")
            lines.append("")
        for i, p in enumerate(items):
            lines.append(f"{{{{< include {p['slug']}/{BODY_PARTIAL} >}}}}")
            lines.append("")
            if i < len(items) - 1:
                lines.append("---")
                lines.append("")

    while lines and lines[-1] in ("", "---"):
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def render_root_index(root: Path, courses: list[Path]) -> str:
    lines: list[str] = []
    lines.append("---")
    lines.append('title: "Courses"')
    lines.append("---")
    lines.append("")
    lines.append(
        html_comment(
            [
                "AUTOGENERATED: public course catalog page.",
                "Generator: ../scripts/build_course_index.py",
                "Sources: courses/*/_course.yml for course/module metadata and",
                "courses/*/**/index.qmd frontmatter for lesson order/title/module.",
                "Regenerate with: uv run python scripts/build_course_index.py --all",
                "Do not edit this file by hand; edit the sources above and regenerate.",
            ]
        ).rstrip()
    )
    lines.append("")

    for course_dir in sorted(courses, key=lambda p: p.name):
        manifest = yaml.safe_load((course_dir / "_course.yml").read_text(encoding="utf-8"))
        pages = collect_pages(course_dir)
        by_module: dict = {}
        for p in pages:
            by_module.setdefault(p["module"], []).append(p)

        course_slug = course_dir.relative_to(root / "courses").as_posix()
        lines.append(f"## {course_slug.upper()}")
        lines.append("")
        lines.append(
            f"- [Полный курс: {manifest['title']}]({course_slug}/index.qmd)"
        )
        lines.append("")

        counter = 1
        for m in manifest["modules"]:
            items = by_module.get(m["id"], [])
            if not items:
                continue

            lines.append(f"### {m['title']}")
            lines.append("")
            if m.get("list_only"):
                for p in items:
                    lines.append(
                        f"- [{p['title']}]({course_slug}/{p['slug']}/index.qmd)"
                    )
            else:
                for p in items:
                    lines.append(
                        f"{counter}. [{p['title']}]({course_slug}/{p['slug']}/index.qmd)"
                    )
                    counter += 1
            lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def build_root_index(root: Path, courses: list[Path], *, quiet: bool = False) -> bool:
    content = render_root_index(root, courses)
    out = root / "courses" / "index.qmd"
    prev = out.read_text(encoding="utf-8") if out.exists() else ""
    if prev == content:
        return False
    out.write_text(content, encoding="utf-8")
    if not quiet:
        print(f"wrote {out}")
    return True


def build_one(course_dir: Path, *, quiet: bool = False) -> bool:
    manifest_path = course_dir / "_course.yml"
    if not manifest_path.exists():
        print(f"missing manifest: {manifest_path}", file=sys.stderr)
        return False
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    pages = collect_pages(course_dir)
    for p in pages:
        inject_back_link(course_dir / p["slug"], p["slug"])
        write_body_partial(course_dir / p["slug"], p["slug"])
    content = render(manifest, pages, course_dir)
    out = course_dir / "index.qmd"
    prev = out.read_text(encoding="utf-8") if out.exists() else ""
    if prev == content:
        return False
    out.write_text(content, encoding="utf-8")
    if not quiet:
        print(f"wrote {out} ({len(pages)} pages)")
    return True


def discover_courses(root: Path) -> list[Path]:
    return [p.parent for p in root.glob("courses/*/_course.yml")]


def watched_files(course_dir: Path) -> list[Path]:
    files = [course_dir / "_course.yml"]
    for idx in course_dir.rglob("index.qmd"):
        if idx != course_dir / "index.qmd":
            files.append(idx)
    return files


def signature(paths: list[Path]) -> tuple:
    return tuple((str(p), p.stat().st_mtime_ns if p.exists() else 0) for p in paths)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("course_dir", nargs="?", help="e.g. courses/ais")
    parser.add_argument("--all", action="store_true", help="build every courses/*/_course.yml")
    parser.add_argument("--watch", action="store_true", help="rebuild on change (stdlib polling)")
    parser.add_argument("--interval", type=float, default=1.0)
    args = parser.parse_args()

    if args.all:
        courses = discover_courses(Path.cwd())
    elif args.course_dir:
        courses = [Path(args.course_dir).resolve()]
    else:
        parser.error("pass a course dir or --all")

    root = Path.cwd()

    for c in courses:
        build_one(c)

    if args.all:
        build_root_index(root, courses)

    if not args.watch:
        return

    print(f"watching {len(courses)} course(s) for frontmatter/_course.yml changes...")
    sigs = {c: signature(watched_files(c)) for c in courses}
    try:
        while True:
            time.sleep(args.interval)
            for c in courses:
                new_sig = signature(watched_files(c))
                if new_sig != sigs[c]:
                    sigs[c] = new_sig
                    build_one(c)
                    if args.all:
                        build_root_index(root, courses)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
